on:
  push:
     branches:
       - master


name: 🚀 Knit and Publish

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown"))'

      - name: Render presentation
        run: |
            cd $GITHUB_WORKSPACE/101_introduction/
            Rscript -e 'rmarkdown::render("CBL_Github_Introduction.Rmd", "html_document")'

      - name: Commit html
        uses: EndBug/add-and-commit@v4
        with:
            message: "Update html slide"
            ref: 'gh-pages'
            add: "*.html"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
